server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      #enable: true
      #location: /Users/YoungminKim
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: <본인 이메일 입력>
#    password: '<본인 Google 앱 비밀번호 입력>'
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    auth-code-expiration-millis: 1800000

logging:
  level:
    org.springframework.web: DEBUG
    com.shoppingmall: DEBUG

mybatis:
  type-aliases-package: com.post.domain
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

os:
  window:
    upload-path: C:/shoppingmall/upload-files/
  mac:
    upload-path: /Users/youngminkim/projects/shoppingmall/upload-files/
  linux:
    upload-path: /var/www/shoppingmall/upload-files/

email:
  title: "쇼핑몰 인증 번호 입니다."