server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/shoppingmall?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB # size of a single file
      max-request-size: 100MB # maximum file size that can be uploaded at once (100 MB)
      #enable: true
      #location: /Users/YoungminKim
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: <본인 이메일 입력>
#    password: '<본인 Google 앱 비밀번호 입력>'
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    auth-code-expiration-millis: 1800000

# logging
logging:
  level:
    org.springframework.web: DEBUG
    com.shoppingmall: DEBUG

# mybatis
mybatis:
  type-aliases-package: com.post.domain # specify that package names can be omitted
  mapper-locations: mybatis-mapper/**/*.xml # location of mapper file
  configuration:
    map-underscore-to-camel-case: true # set model property to camel case

# 실제 물리적으로 파일을 업로드(File.transferTo()) 하기 위한 경로
# - JAR 배포 시에는 프로젝트 내부 파일이 전부 날라가는 현상이 있을 수 있음
# - 외부에서 src/resources/ 경로 접근이 배포 후에는 불가능하기 때문
# - 아래 경로에 파일을 저장하고 URL 매핑을 통해 파일을 처리한다
os:
  window:
    upload-path: C:/shoppingmall/upload-files/
  mac:
    upload-path: /Users/youngminkim/projects/shoppingmall/upload-files/
  linux:
    upload-path: /var/www/shoppingmall/upload-files/

email:
  title: "쇼핑몰 인증 번호 입니다."