server:
  port: 8888

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:shoppingmall;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
