server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false # 개발 환경에서는 thymeleaf 캐싱 기능 off 설정
  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나의 크기(20M)
      max-request-size: 100MB # 한 번에 최대 업로드 가능한 파일 용량(100MB)
      #enable: true # 파일 업로드 가능 여부 선택
      #location: /Users/YoungminKim # 업로드 된 파일의 임시 저장 경로(/Users/YoungminKim)

# logging
logging:
  level:
    com.shoppingmall: DEBUG

# upload path - dev
upload:
  directory: C:/shoppingmall/upload-files
