server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3307/shoppingmall?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/shoppingmall?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false # 개발 환경에서는 thymeleaf 캐싱 기능 off 설정
  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나의 크기(20M)
      max-request-size: 100MB # 한 번에 최대 업로드 가능한 파일 용량(100MB)
      #enable: true # 파일 업로드 가능 여부 선택
      #location: /Users/YoungminKim # 업로드 된 파일의 임시 저장 경로(/Users/YoungminKim)

# logging
logging:
  level:
    com.shoppingmall: DEBUG

# 실제 물리적으로 파일을 업로드(transferTo) 하기 위한 경로
# JAR 배포 시에는 프로젝트 내부 파일이 전부 날라가는 현상이 있을 수 있음
# 외부에서 src/resources/ 경로 접근이 배포 후에는 불가능하기 때문에
# 아래 경로에 파일을 저장하고 URL 매핑을 통해 파일을 처리한다
os:
  window:
    upload-path: C:/shoppingmall/upload-files/
  mac:
    upload-path: /Users/youngminkim/projects/shoppingmall/upload-files/
  linux:
    upload-path: /var/www/upload-files/

email:
  title: "쇼핑몰 인증 번호 입니다."