spring:
  profiles:
    default: local
    group:
      local:
        - oauth
      dev:
        - oauth
      prod:
        - oauth

  devtools:
    livereload:
      enabled: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: <메일을 보내고자 하는 이메일 입력 : GOOGLE>
#    password: '<GOOGLE 앱 비밀번호 입력>'
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    auth-code-expiration-millis: 1800000