spring:
  profiles:
    include: dev, oauth
  #    active: dev, oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true # 실행되는 쿼리 콘솔 출력
        format_sql: true # 콘솔창 쿼리 포맷팅
        default_batch_fetch_size: 1000 # JPA -> n + 1 문제
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false # 개발 환경에서는 thymeleaf 캐싱 기능 off 설정
  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나의 크기(20M)
      max-request-size: 100MB # 한 번에 최대 업로드 가능한 파일 용량(100MB)
      #enable: true # 파일 업로드 가능 여부 선택
      #location: /Users/YoungminKim # 업로드 된 파일의 임시 저장 경로(/Users/YoungminKim)

# mybatis
mybatis:
  type-aliases-package: com.post.domain # 패키지명 생략할 수 있도록 지정
  mapper-locations: mybatis-mapper/**/*.xml # mapper.xml 위치 지정
  configuration:
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정

# logging
logging:
  level:
    com.multi: DEBUG
