spring:
  profiles:
    include: dev, oauth
  #    active: dev, oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true # 실행되는 쿼리 콘솔 출력
        format_sql: true # 콘솔창 쿼리 포맷팅
        default_batch_fetch_size: 1000 # JPA -> n + 1 문제
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false # 개발 환경에서는 thymeleaf 캐싱 기능 off 설정
  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나의 크기(20M)
      max-request-size: 100MB # 한 번에 최대 업로드 가능한 파일 용량(100MB)
      #enable: true # 파일 업로드 가능 여부 선택
      #location: /Users/YoungminKim # 업로드 된 파일의 임시 저장 경로(/Users/YoungminKim)
  mail:
    host: smtp.gmail.com # gmail SMTP Server HOST
    port: 587 # SMPT Server PORT
    username: youngmin1085@gmail.com # 이메일을 보내는 용으로 사용되는 계정
    password: '비밀번호' # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000 # 연결이 불안정한 경우 대기 시간이 길어질 수 있기 때문에 너무 크게 설정하면 전송 속도가 느려질 수 있다.
          timeout: 5000 # 서버에서 응답이 오지 않는 경우 대기 시간을 제한하기 위해 사용된다.
          writetimeout: 5000 # 이메일을 SMTP 서버로 전송하는 데 걸리는 시간을 제한하는데 사용된다.
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분, 이메일 인증 코드의 만료 시간

# mybatis
mybatis:
  type-aliases-package: com.post.domain # 패키지명 생략할 수 있도록 지정
  mapper-locations: mybatis-mapper/**/*.xml # mapper.xml 위치 지정
  configuration:
    map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정

# logging
logging:
  level:
    com.multi: DEBUG

email:
  title: "Shop with me 이메일 인증 번호"